# Generated by Django 6.0.1 on 2026-02-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=20)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('target', models.FloatField(blank=True, null=True)),
                ('stoploss', models.FloatField(blank=True, null=True)),
                ('mtm', models.FloatField(default=0.0)),
                ('status', models.CharField(default='OPEN', max_length=20)),
            ],
        ),
    ]
