# Generated by Django 6.0.1 on 2026-02-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='side',
            field=models.CharField(blank=True, choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10, null=True),
        ),
    ]
