# Generated by Django 6.0.1 on 2026-02-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_position_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='side',
        ),
    ]
