# Generated by Django 6.0.1 on 2026-02-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_position_side'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AddField(
            model_name='position',
            name='lots',
            field=models.PositiveIntegerField(default=1, help_text='Number of lots traded', verbose_name='Number of Lots'),
        ),
        migrations.AddField(
            model_name='position',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total shares/units/contracts (lots × lot size)', verbose_name='Total Quantity'),
        ),
    ]
